export const controls = [
  // DOMAIN 1: Governance & Accountability (14)
  { id:'PDPL-G.1',source:'PDPL',domainNumber:1,domainName:'Governance & Accountability',ref:'G.1',objectiveEn:'Appoint a Data Protection Officer (DPO) — CRITICAL and MANDATORY for all healthcare organizations.',regArticles:'Reg. Art. 32(1)(c)',riskLevel:'CRITICAL',pointsYes:10,pointsPartial:5,evidenceGuidanceEn:'DPO appointment letter, published contact details, reporting line documentation',responsibleRoles:['dpo','org_admin'],mandatoryForTypes:['government_hospital','private_hospital','clinic_small','clinic_large','insurer','pharma','health_tech'],trainingModuleIds:['TRN-010'],weightMultiplier:1.0 },
  { id:'PDPL-G.2',source:'PDPL',domainNumber:1,domainName:'Governance & Accountability',ref:'G.2',objectiveEn:'Maintain ROPA — retained during processing + 5 years after completion.',regArticles:'Reg. Art. 33',riskLevel:'HIGH',pointsYes:7,pointsPartial:4,evidenceGuidanceEn:'ROPA document, retention policy showing 5-year post-completion',responsibleRoles:['dpo','data_steward'],trainingModuleIds:['TRN-001'],weightMultiplier:1.0 },
  { id:'PDPL-G.3',source:'PDPL',domainNumber:1,domainName:'Governance & Accountability',ref:'G.3',objectiveEn:'Conduct DPIA for any of the 7 Reg. Art. 25(1) triggers. Health orgs always trigger via sensitive data.',regArticles:'Reg. Art. 25(1)',riskLevel:'CRITICAL',pointsYes:10,pointsPartial:5,evidenceGuidanceEn:'Completed DPIA, trigger analysis for all 7 conditions, DPO sign-off',responsibleRoles:['dpo','ciso'],trainingModuleIds:['TRN-009'],weightMultiplier:1.0 },
  { id:'PDPL-G.4',source:'PDPL',domainNumber:1,domainName:'Governance & Accountability',ref:'G.4',objectiveEn:'Establish organizational and technical security policies.',regArticles:'Reg. Art. 23(1)',riskLevel:'HIGH',pointsYes:7,pointsPartial:4,evidenceGuidanceEn:'Information security policy, data protection policy, management approval',responsibleRoles:['ciso','dpo'],trainingModuleIds:['TRN-004'],weightMultiplier:1.0 },
  { id:'PDPL-G.5',source:'PDPL',domainNumber:1,domainName:'Governance & Accountability',ref:'G.5',objectiveEn:'Periodic assessment of security measure effectiveness.',pdplArticles:'Art. 19',riskLevel:'MEDIUM',pointsYes:4,pointsPartial:2,evidenceGuidanceEn:'Security assessment reports, vulnerability scan results',responsibleRoles:['ciso'],trainingModuleIds:['TRN-004'],weightMultiplier:1.0 },
  { id:'PDPL-G.6',source:'PDPL',domainNumber:1,domainName:'Governance & Accountability',ref:'G.6',objectiveEn:'Define personnel confidentiality obligations including post-employment.',pdplArticles:'Art. 41',riskLevel:'MEDIUM',pointsYes:4,pointsPartial:2,evidenceGuidanceEn:'Signed NDAs, employment contracts with confidentiality clauses',responsibleRoles:['dpo','org_admin'],trainingModuleIds:['TRN-012'],weightMultiplier:1.0 },
  { id:'PDPL-G.7',source:'PDPL',domainNumber:1,domainName:'Governance & Accountability',ref:'G.7',objectiveEn:'Privacy Notice with 8 base elements + 3 conditional high-risk elements (11 total).',regArticles:'Reg. Art. 4',riskLevel:'HIGH',pointsYes:7,pointsPartial:4,evidenceGuidanceEn:'Published privacy notice in AR/EN, checklist showing all elements',responsibleRoles:['dpo'],trainingModuleIds:['TRN-001'],weightMultiplier:1.0 },
  { id:'PDPL-G.8',source:'PDPL',domainNumber:1,domainName:'Governance & Accountability',ref:'G.8',objectiveEn:'Register of all international data transfers with legal basis per transfer.',pdplArticles:'Art. 29',regArticles:'Transfer Reg. Art. 2',riskLevel:'HIGH',pointsYes:7,pointsPartial:4,evidenceGuidanceEn:'International transfer register with destination, legal basis, safeguards',responsibleRoles:['dpo'],trainingModuleIds:['TRN-008'],weightMultiplier:1.0 },
  { id:'PDPL-G.9',source:'PDPL',domainNumber:1,domainName:'Governance & Accountability',ref:'G.9',objectiveEn:'Data subject complaint handling process and response procedure.',pdplArticles:'Art. 34',regArticles:'Reg. Art. 37',riskLevel:'MEDIUM',pointsYes:4,pointsPartial:2,evidenceGuidanceEn:'Complaint handling procedure, complaint register, response templates',responsibleRoles:['dpo'],trainingModuleIds:['TRN-006'],weightMultiplier:1.0 },
  { id:'PDPL-G.10',source:'PDPL',domainNumber:1,domainName:'Governance & Accountability',ref:'G.10',objectiveEn:'Verify legal guardian for individuals lacking legal capacity.',regArticles:'Reg. Art. 13',riskLevel:'HIGH',pointsYes:7,pointsPartial:4,evidenceGuidanceEn:'Guardian verification procedure, consent forms for guardians',responsibleRoles:['dpo','compliance_officer'],conditionalOn:{processesMinors:true},trainingModuleIds:['TRN-002'],weightMultiplier:1.0 },
  { id:'PDPL-G.11',source:'PDPL',domainNumber:1,domainName:'Governance & Accountability',ref:'G.11',objectiveEn:'Document legal basis for public interest processing.',pdplArticles:'Art. 10(3)',regArticles:'Reg. Art. 21',riskLevel:'MEDIUM',pointsYes:4,pointsPartial:2,evidenceGuidanceEn:'Legal basis documentation per processing activity',responsibleRoles:['dpo'],trainingModuleIds:['TRN-001'],weightMultiplier:1.0 },
  { id:'PDPL-G.12',source:'PDPL',domainNumber:1,domainName:'Governance & Accountability',ref:'G.12',objectiveEn:'Consult SDAIA when DPIA reveals unmitigated high residual risk.',pdplArticles:'Art. 22',regArticles:'Reg. Art. 25(4)',riskLevel:'HIGH',pointsYes:7,pointsPartial:4,evidenceGuidanceEn:'SDAIA consultation records, DPIA residual risk assessment',responsibleRoles:['dpo'],trainingModuleIds:['TRN-009'],weightMultiplier:1.0 },
  { id:'PDPL-G.13',source:'PDPL',domainNumber:1,domainName:'Governance & Accountability',ref:'G.13',objectiveEn:'Register of sectoral laws providing greater protection than PDPL.',pdplArticles:'Art. 3',riskLevel:'MEDIUM',pointsYes:4,pointsPartial:2,evidenceGuidanceEn:'Register of applicable sectoral laws',responsibleRoles:['dpo'],trainingModuleIds:['TRN-001'],weightMultiplier:1.0 },
  { id:'PDPL-G.14',source:'PDPL',domainNumber:1,domainName:'Governance & Accountability',ref:'G.14',objectiveEn:'Formal process for data subject compensation claims and SDAIA communications.',pdplArticles:'Art. 35-40',riskLevel:'HIGH',pointsYes:7,pointsPartial:4,evidenceGuidanceEn:'Compensation claims procedure, SDAIA communication log',responsibleRoles:['dpo','org_admin'],trainingModuleIds:['TRN-010'],weightMultiplier:1.0 },

  // DOMAIN 2: Lawful Basis & Consent (10)
  { id:'PDPL-C.1',source:'PDPL',domainNumber:2,domainName:'Lawful Basis & Consent Management',ref:'C.1',objectiveEn:'Explicit consent for: (1) sensitive/health data, (2) credit data, (3) automated decisions.',regArticles:'Reg. Art. 11(2)',riskLevel:'CRITICAL',pointsYes:10,pointsPartial:5,evidenceGuidanceEn:'Explicit consent forms covering all 3 triggers, consent management system',responsibleRoles:['dpo','compliance_officer'],mandatoryForTypes:['government_hospital','private_hospital','clinic_small','clinic_large','insurer','pharma','health_tech'],trainingModuleIds:['TRN-001','TRN-002'],weightMultiplier:1.0 },
  { id:'PDPL-C.2',source:'PDPL',domainNumber:2,domainName:'Lawful Basis & Consent Management',ref:'C.2',objectiveEn:'Consent withdrawal mechanism — as easy as or easier than giving consent.',regArticles:'Reg. Art. 12',riskLevel:'HIGH',pointsYes:7,pointsPartial:4,evidenceGuidanceEn:'Withdrawal mechanism documentation, UI/UX comparison',responsibleRoles:['dpo'],trainingModuleIds:['TRN-002'],weightMultiplier:1.0 },
  { id:'PDPL-C.3',source:'PDPL',domainNumber:2,domainName:'Lawful Basis & Consent Management',ref:'C.3',objectiveEn:'Consent freely given, specific, informed, unambiguous — documented with timestamp.',regArticles:'Reg. Art. 11(1)',riskLevel:'HIGH',pointsYes:7,pointsPartial:4,evidenceGuidanceEn:'Consent forms with clear language, timestamp logs',responsibleRoles:['dpo','compliance_officer'],trainingModuleIds:['TRN-002'],weightMultiplier:1.0 },
  { id:'PDPL-C.4',source:'PDPL',domainNumber:2,domainName:'Lawful Basis & Consent Management',ref:'C.4',objectiveEn:'Independent consent per processing purpose.',regArticles:'Reg. Art. 11(1)(e)',riskLevel:'HIGH',pointsYes:7,pointsPartial:4,evidenceGuidanceEn:'Separate consent forms per purpose',responsibleRoles:['dpo'],trainingModuleIds:['TRN-002'],weightMultiplier:1.0 },
  { id:'PDPL-C.5',source:'PDPL',domainNumber:2,domainName:'Lawful Basis & Consent Management',ref:'C.5',objectiveEn:'Data minimization — collect only the minimum necessary.',regArticles:'Reg. Art. 19',riskLevel:'MEDIUM',pointsYes:4,pointsPartial:2,evidenceGuidanceEn:'Data minimization policy, field-level justification',responsibleRoles:['dpo','data_steward'],trainingModuleIds:['TRN-001'],weightMultiplier:1.0 },
  { id:'PDPL-C.6',source:'PDPL',domainNumber:2,domainName:'Lawful Basis & Consent Management',ref:'C.6',objectiveEn:'Purpose limitation — process only for the specified purpose.',regArticles:'Reg. Art. 18',riskLevel:'HIGH',pointsYes:7,pointsPartial:4,evidenceGuidanceEn:'Purpose limitation policy, processing activity register',responsibleRoles:['dpo'],trainingModuleIds:['TRN-001'],weightMultiplier:1.0 },
  { id:'PDPL-C.7',source:'PDPL',domainNumber:2,domainName:'Lawful Basis & Consent Management',ref:'C.7',objectiveEn:'Separate explicit consent for direct marketing.',regArticles:'Reg. Art. 28, 29',riskLevel:'MEDIUM',pointsYes:4,pointsPartial:2,evidenceGuidanceEn:'Marketing consent forms, opt-in mechanism',responsibleRoles:['dpo','compliance_officer'],trainingModuleIds:['TRN-001'],weightMultiplier:1.0 },
  { id:'PDPL-C.8',source:'PDPL',domainNumber:2,domainName:'Lawful Basis & Consent Management',ref:'C.8',objectiveEn:'Identify sender and provide clear opt-out in all marketing.',regArticles:'Reg. Art. 28(3)',riskLevel:'LOW',pointsYes:1,pointsPartial:1,evidenceGuidanceEn:'Sample marketing materials with sender ID and opt-out',responsibleRoles:['compliance_officer'],trainingModuleIds:['TRN-001'],weightMultiplier:1.0 },
  { id:'PDPL-C.9',source:'PDPL',domainNumber:2,domainName:'Lawful Basis & Consent Management',ref:'C.9',objectiveEn:'Stop marketing immediately on opt-out.',regArticles:'Reg. Art. 29(3)',riskLevel:'MEDIUM',pointsYes:4,pointsPartial:2,evidenceGuidanceEn:'Opt-out processing procedure, SLA documentation',responsibleRoles:['compliance_officer'],trainingModuleIds:['TRN-001'],weightMultiplier:1.0 },
  { id:'PDPL-C.10',source:'PDPL',domainNumber:2,domainName:'Lawful Basis & Consent Management',ref:'C.10',objectiveEn:'Conduct Legitimate Interest Assessments (LIA) before relying on legitimate interest.',regArticles:'Reg. Art. 16',riskLevel:'HIGH',pointsYes:7,pointsPartial:4,evidenceGuidanceEn:'Completed LIA templates, balancing test documentation',responsibleRoles:['dpo'],trainingModuleIds:['TRN-001'],weightMultiplier:1.0 },
];
