export const controls2 = [
  // DOMAIN 3: Data Subject Rights (13)
  { id:'PDPL-R.1',source:'PDPL',domainNumber:3,domainName:'Data Subject Rights Fulfillment',ref:'R.1',objectiveEn:'Provide data subjects access to their personal data.',regArticles:'Reg. Art. 5',riskLevel:'HIGH',pointsYes:7,pointsPartial:4,evidenceGuidanceEn:'Data access request procedure, response templates',responsibleRoles:['dpo','data_steward'],trainingModuleIds:['TRN-006'],weightMultiplier:1.0 },
  { id:'PDPL-R.2',source:'PDPL',domainNumber:3,domainName:'Data Subject Rights Fulfillment',ref:'R.2',objectiveEn:'Provide portable data in structured, machine-readable format.',regArticles:'Reg. Art. 6',riskLevel:'MEDIUM',pointsYes:4,pointsPartial:2,evidenceGuidanceEn:'Data export capability in JSON/CSV/XML',responsibleRoles:['data_custodian'],trainingModuleIds:['TRN-006'],weightMultiplier:1.0 },
  { id:'PDPL-R.3',source:'PDPL',domainNumber:3,domainName:'Data Subject Rights Fulfillment',ref:'R.3',objectiveEn:'Correct inaccurate data without undue delay, notify recipients.',regArticles:'Reg. Art. 7, 22',riskLevel:'MEDIUM',pointsYes:4,pointsPartial:2,evidenceGuidanceEn:'Correction procedure, recipient notification mechanism',responsibleRoles:['data_steward'],trainingModuleIds:['TRN-006'],weightMultiplier:1.0 },
  { id:'PDPL-R.4',source:'PDPL',domainNumber:3,domainName:'Data Subject Rights Fulfillment',ref:'R.4',objectiveEn:'Delete/destroy data when no longer necessary or consent withdrawn.',regArticles:'Reg. Art. 8',riskLevel:'HIGH',pointsYes:7,pointsPartial:4,evidenceGuidanceEn:'Deletion procedure, destruction certificates',responsibleRoles:['data_custodian','dpo'],trainingModuleIds:['TRN-006'],weightMultiplier:1.0 },
  { id:'PDPL-R.5',source:'PDPL',domainNumber:3,domainName:'Data Subject Rights Fulfillment',ref:'R.5',objectiveEn:'DSR response max 30 days (extendable +30). Refusal procedure. Oral DSR documentation.',regArticles:'Reg. Art. 3(1)(a), 3(2)',riskLevel:'MEDIUM',pointsYes:4,pointsPartial:2,evidenceGuidanceEn:'DSR tracking system, SLA monitoring, extension templates',responsibleRoles:['dpo'],trainingModuleIds:['TRN-006'],weightMultiplier:1.0 },
  { id:'PDPL-R.6',source:'PDPL',domainNumber:3,domainName:'Data Subject Rights Fulfillment',ref:'R.6',objectiveEn:'Notify prior recipients of corrections and deletions.',regArticles:'Reg. Art. 22(2)(b)',riskLevel:'LOW',pointsYes:1,pointsPartial:1,evidenceGuidanceEn:'Recipient notification log',responsibleRoles:['data_steward'],trainingModuleIds:['TRN-006'],weightMultiplier:1.0 },
  { id:'PDPL-R.7',source:'PDPL',domainNumber:3,domainName:'Data Subject Rights Fulfillment',ref:'R.7',objectiveEn:'Restrict processing when accuracy is contested.',regArticles:'Reg. Art. 7(1)',riskLevel:'MEDIUM',pointsYes:4,pointsPartial:2,evidenceGuidanceEn:'Processing restriction procedure, system flagging capability',responsibleRoles:['data_steward'],trainingModuleIds:['TRN-006'],weightMultiplier:1.0 },
  { id:'PDPL-R.8',source:'PDPL',domainNumber:3,domainName:'Data Subject Rights Fulfillment',ref:'R.8',objectiveEn:'Inform data subjects of their rights at point of collection.',regArticles:'Reg. Art. 4(1)(e)',riskLevel:'LOW',pointsYes:1,pointsPartial:1,evidenceGuidanceEn:'Rights information in collection forms',responsibleRoles:['dpo','compliance_officer'],trainingModuleIds:['TRN-001'],weightMultiplier:1.0 },
  { id:'PDPL-R.9',source:'PDPL',domainNumber:3,domainName:'Data Subject Rights Fulfillment',ref:'R.9',objectiveEn:'Verify requester identity before fulfilling DSRs.',regArticles:'Reg. Art. 3(1)(c)',riskLevel:'MEDIUM',pointsYes:4,pointsPartial:2,evidenceGuidanceEn:'Identity verification procedure',responsibleRoles:['dpo','compliance_officer'],trainingModuleIds:['TRN-006'],weightMultiplier:1.0 },
  { id:'PDPL-R.10',source:'PDPL',domainNumber:3,domainName:'Data Subject Rights Fulfillment',ref:'R.10',objectiveEn:'Handle DSRs from legal guardians or authorized representatives.',regArticles:'Reg. Art. 13',riskLevel:'HIGH',pointsYes:7,pointsPartial:4,evidenceGuidanceEn:'Guardian/representative verification procedure',responsibleRoles:['dpo'],conditionalOn:{processesMinors:true},trainingModuleIds:['TRN-006'],weightMultiplier:1.0 },
  { id:'PDPL-R.11',source:'PDPL',domainNumber:3,domainName:'Data Subject Rights Fulfillment',ref:'R.11',objectiveEn:'Enable direct data transmission to another controller.',regArticles:'Reg. Art. 6',riskLevel:'MEDIUM',pointsYes:4,pointsPartial:2,evidenceGuidanceEn:'Direct transmission capability, API documentation',responsibleRoles:['data_custodian'],trainingModuleIds:['TRN-006'],weightMultiplier:1.0 },
  { id:'PDPL-R.12',source:'PDPL',domainNumber:3,domainName:'Data Subject Rights Fulfillment',ref:'R.12',objectiveEn:'Document all DSRs including oral requests in central register.',regArticles:'Reg. Art. 3(1)(d)',riskLevel:'LOW',pointsYes:1,pointsPartial:1,evidenceGuidanceEn:'Central DSR register, oral request documentation',responsibleRoles:['dpo'],trainingModuleIds:['TRN-006'],weightMultiplier:1.0 },
  { id:'PDPL-R.13',source:'PDPL',domainNumber:3,domainName:'Data Subject Rights Fulfillment',ref:'R.13',objectiveEn:'Proactive measures to ensure data accuracy through periodic review.',regArticles:'Reg. Art. 22(5)',riskLevel:'MEDIUM',pointsYes:4,pointsPartial:2,evidenceGuidanceEn:'Data quality policy, periodic accuracy review schedule',responsibleRoles:['data_steward'],trainingModuleIds:['TRN-001'],weightMultiplier:1.0 },

  // DOMAIN 4: Data Security (6 PDPL)
  { id:'PDPL-S.1',source:'PDPL',domainNumber:4,domainName:'Data Security & Cybersecurity (NCA ECC)',ref:'S.1',objectiveEn:'Implement SIEM/logging and monitoring to detect breaches.',regArticles:'Reg. Art. 23(1), 24(1)',riskLevel:'CRITICAL',pointsYes:10,pointsPartial:5,evidenceGuidanceEn:'SIEM deployment evidence, log retention policy, alert configuration',responsibleRoles:['ciso','data_custodian'],trainingModuleIds:['TRN-004'],weightMultiplier:1.0 },
  { id:'PDPL-S.2',source:'PDPL',domainNumber:4,domainName:'Data Security & Cybersecurity (NCA ECC)',ref:'S.2',objectiveEn:'Incident Response Plan for breaches with tested procedures.',regArticles:'Reg. Art. 24',riskLevel:'CRITICAL',pointsYes:10,pointsPartial:5,evidenceGuidanceEn:'IRP document, tabletop exercise results, SDAIA notification templates',responsibleRoles:['ciso','dpo'],trainingModuleIds:['TRN-005'],weightMultiplier:1.0 },
  { id:'PDPL-S.3',source:'PDPL',domainNumber:4,domainName:'Data Security & Cybersecurity (NCA ECC)',ref:'S.3',objectiveEn:'IAM controls based on least-privilege with role-based access and task segregation.',regArticles:'Reg. Art. 23(1), 26(3)',riskLevel:'HIGH',pointsYes:7,pointsPartial:4,evidenceGuidanceEn:'IAM policy, role matrix, access review logs',responsibleRoles:['ciso','data_custodian'],trainingModuleIds:['TRN-004'],weightMultiplier:1.0 },
  { id:'PDPL-S.4',source:'PDPL',domainNumber:4,domainName:'Data Security & Cybersecurity (NCA ECC)',ref:'S.4',objectiveEn:'Classify all data based on sensitivity and risk levels.',regArticles:'Reg. Art. 23(1)',riskLevel:'HIGH',pointsYes:7,pointsPartial:4,evidenceGuidanceEn:'Data classification policy, classification matrix',responsibleRoles:['data_steward','data_custodian'],trainingModuleIds:['TRN-003'],weightMultiplier:1.0 },
  { id:'PDPL-S.5',source:'PDPL',domainNumber:4,domainName:'Data Security & Cybersecurity (NCA ECC)',ref:'S.5',objectiveEn:'Technical protection measures (encryption, pseudonymization) per classification.',regArticles:'Reg. Art. 23(1)',riskLevel:'HIGH',pointsYes:7,pointsPartial:4,evidenceGuidanceEn:'Encryption standards, implementation evidence',responsibleRoles:['ciso','data_custodian'],trainingModuleIds:['TRN-004'],weightMultiplier:1.0 },
  { id:'PDPL-S.6',source:'PDPL',domainNumber:4,domainName:'Data Security & Cybersecurity (NCA ECC)',ref:'S.6',objectiveEn:'Physical security for all locations containing personal data.',regArticles:'Reg. Art. 23(1)',riskLevel:'MEDIUM',pointsYes:4,pointsPartial:2,evidenceGuidanceEn:'Physical security policy, access control logs for server rooms',responsibleRoles:['ciso'],trainingModuleIds:['TRN-004'],weightMultiplier:1.0 },

  // DOMAIN 5: Third-Party & Transfer (9)
  { id:'PDPL-T.1',source:'PDPL',domainNumber:5,domainName:'Third-Party & Data Transfer Compliance',ref:'T.1',objectiveEn:'Execute DPAs with all processors — verify all 9 mandatory clauses.',regArticles:'Reg. Art. 17',riskLevel:'HIGH',pointsYes:7,pointsPartial:4,evidenceGuidanceEn:'Signed DPAs, 9-clause verification checklist per DPA',responsibleRoles:['dpo','compliance_officer'],trainingModuleIds:['TRN-007'],weightMultiplier:1.0 },
  { id:'PDPL-T.2',source:'PDPL',domainNumber:5,domainName:'Third-Party & Data Transfer Compliance',ref:'T.2',objectiveEn:'Cloud provider contracts include PDPL-mandated clauses.',regArticles:'Reg. Art. 17',transferRegArticles:'Transfer Reg. Art. 5',riskLevel:'CRITICAL',pointsYes:10,pointsPartial:5,evidenceGuidanceEn:'Cloud contracts with PDPL clauses, data residency confirmation',responsibleRoles:['ciso','dpo'],trainingModuleIds:['TRN-007'],weightMultiplier:1.0 },
  { id:'PDPL-T.3',source:'PDPL',domainNumber:5,domainName:'Third-Party & Data Transfer Compliance',ref:'T.3',objectiveEn:'Risk assessments before engaging new processors.',regArticles:'Reg. Art. 17(3)',riskLevel:'HIGH',pointsYes:7,pointsPartial:4,evidenceGuidanceEn:'Processor risk assessment template, completed assessments',responsibleRoles:['dpo','ciso'],trainingModuleIds:['TRN-007'],weightMultiplier:1.0 },
  { id:'PDPL-T.4',source:'PDPL',domainNumber:5,domainName:'Third-Party & Data Transfer Compliance',ref:'T.4',objectiveEn:'Periodic monitoring and audit of processor compliance.',regArticles:'Reg. Art. 17(3)',riskLevel:'MEDIUM',pointsYes:4,pointsPartial:2,evidenceGuidanceEn:'Processor audit schedule, audit reports',responsibleRoles:['dpo','compliance_officer'],trainingModuleIds:['TRN-007'],weightMultiplier:1.0 },
  { id:'PDPL-T.5',source:'PDPL',domainNumber:5,domainName:'Third-Party & Data Transfer Compliance',ref:'T.5',objectiveEn:'Cross-border transfers protected by SDAIA adequacy or SDAIA standard model SCCs.',transferRegArticles:'Transfer Reg. Art. 3, 5(1)(b)',riskLevel:'CRITICAL',pointsYes:10,pointsPartial:5,evidenceGuidanceEn:'SDAIA adequacy decision ref or signed SDAIA standard model SCCs',responsibleRoles:['dpo'],conditionalOn:{crossBorderTransfers:true},trainingModuleIds:['TRN-008'],weightMultiplier:1.0 },
  { id:'PDPL-T.6',source:'PDPL',domainNumber:5,domainName:'Third-Party & Data Transfer Compliance',ref:'T.6',objectiveEn:'Conduct Transfer Impact Assessments before each cross-border transfer.',transferRegArticles:'Transfer Reg. Art. 8',riskLevel:'HIGH',pointsYes:7,pointsPartial:4,evidenceGuidanceEn:'Transfer Impact Assessment per destination',responsibleRoles:['dpo'],conditionalOn:{crossBorderTransfers:true},trainingModuleIds:['TRN-008'],weightMultiplier:1.0 },
  { id:'PDPL-T.7',source:'PDPL',domainNumber:5,domainName:'Third-Party & Data Transfer Compliance',ref:'T.7',objectiveEn:'Limit cross-border transfers to minimum necessary data.',transferRegArticles:'Transfer Reg. Art. 2(2)',riskLevel:'MEDIUM',pointsYes:4,pointsPartial:2,evidenceGuidanceEn:'Data minimization assessment per transfer',responsibleRoles:['dpo','data_steward'],conditionalOn:{crossBorderTransfers:true},trainingModuleIds:['TRN-008'],weightMultiplier:1.0 },
  { id:'PDPL-T.8',source:'PDPL',domainNumber:5,domainName:'Third-Party & Data Transfer Compliance',ref:'T.8',objectiveEn:'Monitor 4 mandatory transfer suspension triggers.',transferRegArticles:'Transfer Reg. Art. 7',riskLevel:'CRITICAL',pointsYes:10,pointsPartial:5,evidenceGuidanceEn:'Transfer monitoring procedure, suspension trigger checklist',responsibleRoles:['dpo'],conditionalOn:{crossBorderTransfers:true},trainingModuleIds:['TRN-008'],weightMultiplier:1.0 },
  { id:'PDPL-T.9',source:'PDPL',domainNumber:5,domainName:'Third-Party & Data Transfer Compliance',ref:'T.9',objectiveEn:'Conduct Transfer Risk Assessment for all cross-border transfers.',transferRegArticles:'Transfer Reg. Art. 8',riskLevel:'CRITICAL',pointsYes:10,pointsPartial:5,evidenceGuidanceEn:'Completed TRA signed by DPO covering purpose, legal basis, scope, safeguards',responsibleRoles:['dpo'],conditionalOn:{crossBorderTransfers:true},trainingModuleIds:['TRN-008'],weightMultiplier:1.0 },

  // DOMAIN 6: Breach Management (4)
  { id:'PDPL-B.1',source:'PDPL',domainNumber:6,domainName:'Breach Management & Notification',ref:'B.1',objectiveEn:'Notify SDAIA within 72 hours — 5 mandatory fields.',regArticles:'Reg. Art. 24(1)',riskLevel:'CRITICAL',pointsYes:10,pointsPartial:5,evidenceGuidanceEn:'SDAIA notification template with 5 fields, breach timeline docs',responsibleRoles:['dpo','ciso'],trainingModuleIds:['TRN-005'],weightMultiplier:1.0 },
  { id:'PDPL-B.2',source:'PDPL',domainNumber:6,domainName:'Breach Management & Notification',ref:'B.2',objectiveEn:'Notify affected data subjects — 4 mandatory fields including recommendations/advice.',regArticles:'Reg. Art. 24(5)',riskLevel:'HIGH',pointsYes:7,pointsPartial:4,evidenceGuidanceEn:'Subject notification template with 4 fields incl. recommendations',responsibleRoles:['dpo'],trainingModuleIds:['TRN-005'],weightMultiplier:1.0 },
  { id:'PDPL-B.3',source:'PDPL',domainNumber:6,domainName:'Breach Management & Notification',ref:'B.3',objectiveEn:'Document all breach facts, effects, corrective measures.',regArticles:'Reg. Art. 24(3)',riskLevel:'MEDIUM',pointsYes:4,pointsPartial:2,evidenceGuidanceEn:'Breach register, incident documentation template',responsibleRoles:['ciso','dpo'],trainingModuleIds:['TRN-005'],weightMultiplier:1.0 },
  { id:'PDPL-B.4',source:'PDPL',domainNumber:6,domainName:'Breach Management & Notification',ref:'B.4',objectiveEn:'Update and test breach response plan regularly.',regArticles:'Reg. Art. 24',riskLevel:'MEDIUM',pointsYes:4,pointsPartial:2,evidenceGuidanceEn:'Test schedule, tabletop exercise reports',responsibleRoles:['ciso','dpo'],trainingModuleIds:['TRN-005'],weightMultiplier:1.0 },

  // DOMAIN 7: Records & Documentation (5)
  { id:'PDPL-D.1',source:'PDPL',domainNumber:7,domainName:'Records & Documentation',ref:'D.1',objectiveEn:'Maintain ROPA during processing + 5 years after completion. SDAIA-accessible.',regArticles:'Reg. Art. 33(1)',riskLevel:'HIGH',pointsYes:7,pointsPartial:4,evidenceGuidanceEn:'ROPA with mandatory fields, 5-year post-completion retention',responsibleRoles:['dpo','data_steward'],trainingModuleIds:['TRN-001'],weightMultiplier:1.0 },
  { id:'PDPL-D.2',source:'PDPL',domainNumber:7,domainName:'Records & Documentation',ref:'D.2',objectiveEn:'Document purposes and lawful basis per processing activity in ROPA.',regArticles:'Reg. Art. 33(5)(c)',riskLevel:'MEDIUM',pointsYes:4,pointsPartial:2,evidenceGuidanceEn:'ROPA entries showing purpose and legal basis per activity',responsibleRoles:['dpo','data_steward'],trainingModuleIds:['TRN-001'],weightMultiplier:1.0 },
  { id:'PDPL-D.3',source:'PDPL',domainNumber:7,domainName:'Records & Documentation',ref:'D.3',objectiveEn:'Record all disclosures to third parties.',regArticles:'Reg. Art. 20(6)',riskLevel:'LOW',pointsYes:1,pointsPartial:1,evidenceGuidanceEn:'Third-party disclosure register',responsibleRoles:['data_steward'],trainingModuleIds:['TRN-001'],weightMultiplier:1.0 },
  { id:'PDPL-D.4',source:'PDPL',domainNumber:7,domainName:'Records & Documentation',ref:'D.4',objectiveEn:'Archive official documents per applicable laws.',pdplArticles:'Art. 18',riskLevel:'MEDIUM',pointsYes:4,pointsPartial:2,evidenceGuidanceEn:'Document archival policy, retention schedule',responsibleRoles:['data_steward','compliance_officer'],trainingModuleIds:['TRN-001'],weightMultiplier:1.0 },
  { id:'PDPL-D.5',source:'PDPL',domainNumber:7,domainName:'Records & Documentation',ref:'D.5',objectiveEn:'Retain DPIA and all impact assessment records.',regArticles:'Reg. Art. 25(2)',riskLevel:'HIGH',pointsYes:7,pointsPartial:4,evidenceGuidanceEn:'DPIA archive, impact assessment records',responsibleRoles:['dpo'],trainingModuleIds:['TRN-009'],weightMultiplier:1.0 },

  // DOMAIN 8: Training (4)
  { id:'PDPL-TR.1',source:'PDPL',domainNumber:8,domainName:'Training & Awareness',ref:'TR.1',objectiveEn:'Role-based PDPL training to all personnel.',pdplArticles:'Art. 41',regArticles:'Reg. Art. 23',riskLevel:'MEDIUM',pointsYes:4,pointsPartial:2,evidenceGuidanceEn:'Training program, role-based curricula, completion certificates',responsibleRoles:['dpo','department_manager'],trainingModuleIds:['TRN-001'],weightMultiplier:1.0 },
  { id:'PDPL-TR.2',source:'PDPL',domainNumber:8,domainName:'Training & Awareness',ref:'TR.2',objectiveEn:'Train staff on breach recognition and response.',regArticles:'Reg. Art. 24',riskLevel:'HIGH',pointsYes:7,pointsPartial:4,evidenceGuidanceEn:'Breach awareness training materials, completion records',responsibleRoles:['ciso','dpo'],trainingModuleIds:['TRN-005'],weightMultiplier:1.0 },
  { id:'PDPL-TR.3',source:'PDPL',domainNumber:8,domainName:'Training & Awareness',ref:'TR.3',objectiveEn:'Ongoing data protection awareness — annual recertification.',pdplArticles:'Art. 41',riskLevel:'MEDIUM',pointsYes:4,pointsPartial:2,evidenceGuidanceEn:'Annual awareness program, recertification schedule',responsibleRoles:['dpo'],trainingModuleIds:['TRN-012'],weightMultiplier:1.0 },
  { id:'HS-PDPL-018',source:'MOH',domainNumber:8,domainName:'Training & Awareness',ref:'HS-018',objectiveEn:'Mandatory role-based PDPL training with annual recertification.',pdplArticles:'Art. 41',mohPolicyRef:'MoH Policy - Training',riskLevel:'HIGH',pointsYes:7,pointsPartial:4,evidenceGuidanceEn:'Role-based training completion, annual recertification evidence',responsibleRoles:['dpo','department_manager'],mandatoryForTypes:['government_hospital','private_hospital','clinic_small','clinic_large','insurer','pharma','health_tech'],trainingModuleIds:['TRN-001'],weightMultiplier:1.2 },

  // DOMAIN 9: Special Processing (4)
  { id:'PDPL-SP.1',source:'PDPL',domainNumber:9,domainName:'Sectoral & Special Processing',ref:'SP.1',objectiveEn:'Pseudonymize/anonymize research data — re-identification must be impossible.',regArticles:'Reg. Art. 9, 30',riskLevel:'MEDIUM',pointsYes:4,pointsPartial:2,evidenceGuidanceEn:'Pseudonymization procedures, re-identification risk assessment',responsibleRoles:['data_steward','dpo'],conditionalOn:{conductsResearch:true},trainingModuleIds:['TRN-011'],weightMultiplier:1.0 },
  { id:'PDPL-SP.2',source:'PDPL',domainNumber:9,domainName:'Sectoral & Special Processing',ref:'SP.2',objectiveEn:'Limit research data to minimum necessary.',regArticles:'Reg. Art. 30',riskLevel:'MEDIUM',pointsYes:4,pointsPartial:2,evidenceGuidanceEn:'Research data minimization policy',responsibleRoles:['data_steward'],conditionalOn:{conductsResearch:true},trainingModuleIds:['TRN-011'],weightMultiplier:1.0 },
  { id:'PDPL-SP.3',source:'PDPL',domainNumber:9,domainName:'Sectoral & Special Processing',ref:'SP.3',objectiveEn:'Do not copy/photograph official ID unless legally required.',regArticles:'Reg. Art. 31',riskLevel:'MEDIUM',pointsYes:4,pointsPartial:2,evidenceGuidanceEn:'ID handling policy',responsibleRoles:['compliance_officer'],trainingModuleIds:['TRN-001'],weightMultiplier:1.0 },
  { id:'PDPL-SP.4',source:'PDPL',domainNumber:9,domainName:'Sectoral & Special Processing',ref:'SP.4',objectiveEn:'Comply with Credit Information Law for credit data.',regArticles:'Reg. Art. 27',riskLevel:'HIGH',pointsYes:7,pointsPartial:4,evidenceGuidanceEn:'Credit data processing procedures',responsibleRoles:['dpo','compliance_officer'],trainingModuleIds:['TRN-001'],weightMultiplier:1.0 },
];
